Repository PiekJ/jambot, pull requests merged in 2024-07, with the labels that each got.

#78 Include database for caching Spotify/Youtube tracks
  docs/getting-started.html
  mvnw
  pom.xml
  src/main/java/dev/joopie/jambot/JambotApplication.java
  src/main/java/dev/joopie/jambot/api/soundboard/ApiSoundBoardService.java
  src/main/java/dev/joopie/jambot/api/soundboard/SoundAuthorDto.java
  src/main/java/dev/joopie/jambot/api/spotify/ApiSpotifyService.java
  src/main/java/dev/joopie/jambot/api/youtube/ApiYouTubeService.java
  src/main/java/dev/joopie/jambot/api/youtube/IdDeserializer.java
  src/main/java/dev/joopie/jambot/api/youtube/SearchResponse.java
  src/main/java/dev/joopie/jambot/api/youtube/SearchResultDto.java
  src/main/java/dev/joopie/jambot/config/JdaConfig.java
  src/main/java/dev/joopie/jambot/exception/ValidationException.java
  src/main/java/dev/joopie/jambot/listener/SearchFeedbackEventListener.java
  src/main/java/dev/joopie/jambot/model/AlbumTrack.java
  src/main/java/dev/joopie/jambot/model/Artist.java
  src/main/java/dev/joopie/jambot/model/Track.java
  src/main/java/dev/joopie/jambot/model/TrackSource.java
  src/main/java/dev/joopie/jambot/model/album/Album.java
  src/main/java/dev/joopie/jambot/model/album/AlbumGroup.java
  src/main/java/dev/joopie/jambot/model/album/AlbumType.java
  src/main/java/dev/joopie/jambot/model/base/BaseModel.java
  src/main/java/dev/joopie/jambot/music/GuildMusicPlayer.java
  src/main/java/dev/joopie/jambot/music/GuildMusicService.java
  src/main/java/dev/joopie/jambot/music/command/JamCommandHandler.java
  src/main/java/dev/joopie/jambot/music/command/PlayCommandHandler.java
  src/main/java/dev/joopie/jambot/music/command/QueueCommandHandler.java
  src/main/java/dev/joopie/jambot/music/command/SearchCommandHandler.java
  src/main/java/dev/joopie/jambot/repository/album/AlbumRepository.java
  src/main/java/dev/joopie/jambot/repository/album/AlbumTrackRepository.java
  src/main/java/dev/joopie/jambot/repository/artist/ArtistRepository.java
  src/main/java/dev/joopie/jambot/repository/track/TrackRepository.java
  src/main/java/dev/joopie/jambot/repository/track/TrackSourceRepository.java
  src/main/java/dev/joopie/jambot/service/SearchService.java
  src/main/java/dev/joopie/jambot/service/SpotifyAPIConverterService.java
  src/main/java/dev/joopie/jambot/service/TrackService.java
  src/main/java/dev/joopie/jambot/service/TrackSourceService.java
  src/main/java/dev/joopie/jambot/soundboard/SoundboardService.java
  src/main/resources/application.properties
  src/main/resources/db/changelog/db.changelog-master.xml
  src/test/java/dev/joopie/jambot/JambotApplicationTests.java
Labels: wait_for_reviewer

#87 Fix remaining bugs of #78
  docs/getting-started.html
  src/main/java/dev/joopie/jambot/command/CommandAutocomplete.java
  src/main/java/dev/joopie/jambot/config/JdaConfig.java
  src/main/java/dev/joopie/jambot/listener/SearchFeedbackEventListener.java
  src/main/java/dev/joopie/jambot/music/GuildMusicService.java
  src/main/java/dev/joopie/jambot/music/command/PlayCommandHandler.java
  src/main/java/dev/joopie/jambot/music/command/RemoveCommandHandler.java
  src/main/java/dev/joopie/jambot/music/command/SearchCommandHandler.java
  src/main/java/dev/joopie/jambot/service/SearchService.java
Labels: review_accepted

#91 Implement play statistics
  src/main/java/dev/joopie/jambot/JambotListener.java
  src/main/java/dev/joopie/jambot/model/PlayHistory.java
  src/main/java/dev/joopie/jambot/music/AudioTrackLoadResultHandler.java
  src/main/java/dev/joopie/jambot/music/GuildMusicPlayer.java
  src/main/java/dev/joopie/jambot/music/GuildMusicService.java
  src/main/java/dev/joopie/jambot/repository/PlayHistoryRepository.java
  src/main/java/dev/joopie/jambot/service/PlayHistoryService.java
  src/main/resources/db/changelog/db.changelog-master.xml
Labels: need_reviewer

#90 Deafen on join
  src/main/java/dev/joopie/jambot/music/GuildMusicPlayer.java
Labels: need_reviewer

#104 Add additional filtering for track name
  src/main/java/dev/joopie/jambot/api/spotify/ApiSpotifyService.java
Labels: review_accepted
